### ISSUE TITLE
Toy CR API를 구현한다

### ISSUE THREAD

**Issue by sypark9646** [toy-land/backend#3]

**Comment by toneyparky** [comment]
## Toy

- `POST` "/toys"

    [Body](https://www.notion.so/02a26cfd7d834662b28f3238dbb22954)

    - SUCCESS

        ```json
        status code : 201

        {
        	"message": "toy 추가 성공"
        }
        ```

        [Fields](https://www.notion.so/3af45dabc3e34bd8b3309cbf249c6dc1)

    - FAIL

        ```json
        status code : 400

        {
        	"message": "적당한 클라이언트 에러 메세지"
        }
        ```

        [Fields](https://www.notion.so/1318ebda1d04498a98d7042058bedf89)

        ```json
        status code : 500

        {
        	"message": "적당한 서버 에러 메세지"
        }
        ```

        [Fields](https://www.notion.so/dd2d5e4f86df48bcae2704dfbce60a82)

- `GET` "/toys" - 전체 조회
    - SUCCESS

        ```json
        복수 조회시 응답 
        status code : 200

        {
        	"toys": [
        		{
        			"id": 1,
        			"title": "",
        			"description": "토이 프로젝트 큐레이팅 웹 서비스",
        			"category": "WEB",
        			"logo_url": "https://avatars.githubusercontent.com/u/69037013?v=4",
        			"active": "2021-02-04T16:15:30",
        		},
        		...
        	]
        }
        ```

        [Fields](https://www.notion.so/ca1488625cbd4b2f92f83b86ae5ab097)

- `GET` "/toys" - 정렬, 필터링

    [Query Params](https://www.notion.so/40009e1906ec49ef801267df97e79c9c)

- `GET` "/toys/{id}"

    [Path Params](https://www.notion.so/f965a9947dcb4145813cceea25f0829b)

    - FAIL

        ```json
        status code : 404

        {
        	"message": "toy를 찾을 수 없습니다."
        }
        ```

        [Fields](https://www.notion.so/8cd661654d1b4d75ab8a5af1c3436f17)

    - SUCCESS

        ```json

        ```

        [Fields](https://www.notion.so/b3f65a9e1a8f45cb898f8b488e6b50a9)

- `GET` "/toys/contain" ⇒ 검색

    [Query Params](https://www.notion.so/ab3e0e97b71d4c22ac323d117b613141)

- `GET` "/toys/auto-complete" ⇒ 자동완성

    [Query Params](https://www.notion.so/d4f3bdbd808f401d9a7d2ddc31638b3e)
